// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.ComponentModel;

namespace Microsoft.Extensions.ApiDescriptions;

/// <summary>
/// Represents a provider for OpenAPI documents to support build-time generation.
/// </summary>
/// <remarks>
/// The Microsoft.Extensions.ApiDescription.Server package and associated configuration
/// execute the `dotnet getdocument` command at build-time to support build-time
/// generation of documents. The `getdocument` tool launches the entry point assembly
/// and queries it for a service that implements the `IDocumentProvider` interface. For
/// historical reasons, the `IDocumentProvider` interface isn't exposed publicly from
/// the framework and the `getdocument` tool instead queries for it using the type name.
/// That means the `IDocumentProvider` interface must be declared under the namespace
/// that it expects. For more information, see https://github.com/dotnet/aspnetcore/blob/82c9b34d7206ba56ea1d641843e1f2fe6d2a0b1c/src/Tools/GetDocumentInsider/src/Commands/GetDocumentCommandWorker.cs#L25.
/// </remarks>
[EditorBrowsable(EditorBrowsableState.Never)]
public interface IDocumentProvider
{
    /// <summary>
    /// Gets the names of the documents that can be generated by this provider. The `getdocument` tool will call `GenerateAsync` for each document name returned by this method.
    /// </summary>
    /// <returns>A collection of document names that can be generated by this provider.</returns>
    IEnumerable<string> GetDocumentNames();

    /// <summary>
    /// Generates the OpenAPI document with the specified name and writes it to the provided `TextWriter`. The `getdocument` tool will call this method for each document name
    /// returned by `GetDocumentNames()`. The implementation of this method should generate the OpenAPI document corresponding to the provided `documentName` and write it to
    /// the `writer`. The `getdocument` tool will then read the generated document from the `writer` and use it for build-time generation.
    /// </summary>
    /// <param name="documentName">The name of the document to generate.</param>
    /// <param name="writer">The `TextWriter` to which the generated document should be written.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    Task GenerateAsync(string documentName, TextWriter writer);

    /// <summary>
    /// Asynchronously generates an OpenAPI document and writes it to the specified text writer.
    /// </summary>
    /// <remarks>The caller is responsible for managing the lifetime of the provided text writer. The method
    /// does not close or dispose the writer after writing.</remarks>
    /// <param name="documentName">The name of the document to generate. Cannot be null or empty.</param>
    /// <param name="writer">The text writer to which the generated OpenAPI document will be written. Cannot be null.</param>
    /// <param name="openApiSpecVersion">The OpenAPI specification version to use when generating the document.</param>
    /// <returns>A task that represents the asynchronous generation operation.</returns>
    Task GenerateAsync(string documentName, TextWriter writer, OpenApiSpecVersion openApiSpecVersion);
}
